### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by leloup314**
This PR

- Updates the README install instructions to work on with a fresh install / Python env because `setup.py` relies on `cython`, `numpy` and `gcc` 
- Adds the Cython output CPP to the .gitignore

### CODE REVIEW

**Comment by YannickDieter** [comment]
Great, thanks for testing and improving the README! Can I merge it already or do you want add more?

**Review by YannickDieter — APPROVED** [review]
Fine for me.

**Comment by leloup314** [comment]
Merge, my boy

**Comment by leloup314** [comment]
You will eventually merge the `unit_tests` branch, right? ;)

**Comment by YannickDieter** [comment]
Yes, thats the plan! Maybe I have some time next week ;)

**Pull request merged**
